[package]
name = "pumpkinpatch"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
diesel = { version = "2.2.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15"
minio = { git = "https://github.com/minio/minio-rs.git" }
